import edgeFadeChunk from './common/edge_fade.glsl';
import luminanceChunk from './common/luminance.glsl';
import noiseChunk from './common/noise.glsl';
import seamCorrectionChunk from './common/seam_correction.glsl';
import cyberpunkFragment from './cyberpunk/fragment.glsl';
import cyberpunkVertex from './cyberpunk/vertex.glsl';
import holographicFragment from './holographic/fragment.glsl';
import holographicVertex from './holographic/vertex.glsl';
import paintingFragment from './painting/fragment.glsl';
import paintingVertex from './painting/vertex.glsl';
import pixelFragment from './pixel/fragment.glsl';
import pixelVertex from './pixel/vertex.glsl';
import sketchFragment from './sketch/fragment.glsl';
import sketchVertex from './sketch/vertex.glsl';
import splatFragment from './splat/fragment.glsl';
import splatVertex from './splat/vertex.glsl';

export const SEAM_CORRECTION_CHUNK = seamCorrectionChunk;
export const NOISE_CHUNK = noiseChunk;
export const LUMINANCE_CHUNK = luminanceChunk;
export const EDGE_FADE_CHUNK = edgeFadeChunk;
export const holographicVertexShader = holographicVertex;
export const holographicFragmentShader = holographicFragment;
export const paintingVertexShader = paintingVertex;
export const paintingFragmentShader = paintingFragment;
export const splatVertexShader = splatVertex;
export const splatFragmentShader = splatFragment;
export const sketchVertexShader = sketchVertex;
export const sketchFragmentShader = sketchFragment;
export const pixelVertexShader = pixelVertex;
export const pixelFragmentShader = pixelFragment;
export const cyberpunkVertexShader = cyberpunkVertex;
export const cyberpunkFragmentShader = cyberpunkFragment;